apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: runtimes
    app: springboot
    version: v1
  name: springboot-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/scrape: "true"
      labels:
        project: runtimes
        app: springboot
        version: v1
    spec:
      containers:
      - image: #IMAGE
        imagePullPolicy: #PULL_POLICY
        name: springboot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    project: runtimes
    app: springboot
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: springboot
