apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: runtimes
    app: vertx
    version: v1
  name: vertx-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertx
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        project: runtimes
        app: vertx
        version: v1
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: vertx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: vertx
  labels:
    project: runtimes
    app: vertx
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: vertx
