apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-v1
spec:
  selector:
    matchLabels:
      app: bank
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: bank
        version: v1
    spec:
      containers:
        - name: bank
          image: quay.io/kiali/demo_fraud_bank:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 50053
              protocol: TCP
              name: grpc
          securityContext:
            privileged: false
          env:
            - name: CURRENT_SERVICE
              value: "bank"
            - name: CURRENT_VERSION
              value: "v1"
            - name: LISTEN_ADDRESS
              value: ":50053"
            - name: ACCOUNTS_ADDRESS
              value: "accounts.fraud-detection:50051"
            - name: CARDS_ADDRESS
              value: "cards.fraud-detection:50052"
            - name: WAIT
              value: "10"
---
apiVersion: v1
kind: Service
metadata:
  name: bank
  labels:
    app: bank
spec:
  ports:
    - name: grpc
      port: 50053
      protocol: TCP
  selector:
    app: bank
---
