apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-v1
spec:
  selector:
    matchLabels:
      app: cards
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: cards
        version: v1
    spec:
      containers:
        - name: cards
          image: quay.io/kiali/demo_fraud_cards:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
              protocol: TCP
              name: grpc
          securityContext:
            privileged: false
          env:
            - name: CURRENT_SERVICE
              value: "cards"
            - name: CURRENT_VERSION
              value: "v1"
            - name: LISTEN_ADDRESS
              value: ":50052"
            - name: WAIT
              value: "10"
---
apiVersion: v1
kind: Service
metadata:
  name: cards
  labels:
    app: cards
spec:
  ports:
    - name: grpc
      port: 50052
      protocol: TCP
  selector:
    app: cards
---
