apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-v1
spec:
  selector:
    matchLabels:
      app: insurance
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: insurance
        version: v1
    spec:
      containers:
        - name: insurance
          image: kiali/demo_fraud_insurance:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 50063
              protocol: TCP
              name: grpc
          securityContext:
            privileged: false
          env:
            - name: CURRENT_SERVICE
              value: "insurance"
            - name: CURRENT_VERSION
              value: "v1"
            - name: LISTEN_ADDRESS
              value: ":50063"
            - name: CLAIMS_ADDRESS
              value: "claims.fraud-detection:50061"
            - name: POLICIES_ADDRESS
              value: "policies.fraud-detection:50062"
            - name: WAIT
              value: "10"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance
  labels:
    app: insurance
spec:
  ports:
    - name: grpc
      port: 50063
      protocol: TCP
  selector:
    app: insurance
---