apiVersion: apps/v1
kind: Deployment
metadata:
  name: policies-v1
spec:
  selector:
    matchLabels:
      app: policies
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: policies
        version: v1
    spec:
      containers:
        - name: policies
          image: kiali/demo_fraud_policies:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 50062
              protocol: TCP
              name: grpc
          securityContext:
            privileged: false
          env:
            - name: CURRENT_SERVICE
              value: "policies"
            - name: CURRENT_VERSION
              value: "v1"
            - name: LISTEN_ADDRESS
              value: ":50062"
            - name: WAIT
              value: "10"
---
apiVersion: v1
kind: Service
metadata:
  name: policies
  labels:
    app: policies
spec:
  ports:
    - name: grpc
      port: 50062
      protocol: TCP
  selector:
    app: policies
---