apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-client
spec:
  selector:
    matchLabels:
      app: a-client
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: a-client
        version: v1
    spec:
      containers:
        - name: a
          image: kiali/demo_error_rates_client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://x-server.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-client
spec:
  selector:
    matchLabels:
      app: b-client
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: b-client
        version: v1
    spec:
      containers:
        - name: b-client
          image: kiali/demo_error_rates_client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://x-server.alpha:8888/status,http://y-server.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-client
spec:
  selector:
    matchLabels:
      app: c-client
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: c-client
        version: v1
    spec:
      containers:
        - name: c-client
          image: kiali/demo_error_rates_client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://y-server.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-client
spec:
  selector:
    matchLabels:
      app: d-client
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: d-client
        version: v1
    spec:
      containers:
        - name: d-client
          image: kiali/demo_error_rates_client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://y-server.alpha:8888/status,http://z-server.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-client
spec:
  selector:
    matchLabels:
      app: e-client
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: e-client
        version: v1
    spec:
      containers:
        - name: e-client
          image: kiali/demo_error_rates_client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://z-server.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-server
spec:
  selector:
    matchLabels:
      app: x-server
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: x-server
        version: v1
    spec:
      containers:
        - name: x-server
          image: kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;404,1"
---
apiVersion: v1
kind: Service
metadata:
  name: x-server
  labels:
    app: x-server
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: x-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-server
spec:
  selector:
    matchLabels:
      app: y-server
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: y-server
        version: v1
    spec:
      containers:
        - name: y-server
          image: kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;500,1"
---
apiVersion: v1
kind: Service
metadata:
  name: y-server
  labels:
    app: y-server
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: y-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: z-server
spec:
  selector:
    matchLabels:
      app: z-server
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: z-server
        version: v1
    spec:
      containers:
        - name: z-server
          image: kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,8;201,1;202,1"
---
apiVersion: v1
kind: Service
metadata:
  name: z-server
  labels:
    app: z-server
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: z-server
